name: Typescript CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "app/**"
      - ".oxlintrc.json"
      - ".oxfmtrc.jsonc"
      - ".nvmrc"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: test-typescript-app-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          package_json_file: app/package.json
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./app/pnpm-lock.yaml
          node-version: lts/*
          cache: "pnpm"
      - name: Install dependencies
        working-directory: ./app
        run: pnpm install --frozen-lockfile
      - name: Type Check
        working-directory: ./app
        run: pnpm run typecheck
      - name: Formatting
        working-directory: ./app
        run: |
          pnpm run fmt:check
      - name: Lint
        working-directory: ./app
        run: |
          pnpm run lint
      - name: Relay Codegen
        working-directory: ./app
        run: |
          pnpm run build:relay
          git diff --exit-code
      - name: Test
        working-directory: ./app
        run: |
          pnpm run test
