name: Typescript Packages CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: test-typescript-packages-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Filter Changes
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            packages:
              - "js/**"
              - "schemas/**"
              - ".oxlintrc.json"
              - ".oxfmtrc.jsonc"
              - ".nvmrc"

  ci:
    name: CI Typescript
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.packages == 'true' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          package_json_file: js/package.json
      - name: Install Dependencies
        working-directory: ./js
        run: pnpm install --frozen-lockfile -r
      - name: Build
        working-directory: ./js
        run: |
          pnpm run -r build
          git diff --exit-code
      - name: Test
        working-directory: ./js
        run: pnpm run -r test
      - name: Formatting
        working-directory: ./js
        run: |
          pnpm run fmt:check
      - name: Type Checking
        working-directory: ./js
        run: |
          pnpm run typecheck
      - name: Linting
        working-directory: ./js
        run: |
          pnpm run lint

  ci-required:
    name: CI Required
    needs:
      - changes
      - ci
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check all required jobs passed or were skipped
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "One or more CI jobs failed"
            exit 1
          fi
          if [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more CI jobs were cancelled"
            exit 1
          fi
          echo "All CI jobs passed or were skipped"
